//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServ1.InventoryFuncs {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryFuncs.InventoryFuncsSoap")]
    public interface InventoryFuncsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventoryUserDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInventoryUserDataTable(int userId, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventoryUserDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetInventoryUserDataTableAsync(int userId, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeInventoryRow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool changeInventoryRow(WebServ1.InventoryFuncs.InventoryRow inventoryRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changeInventoryRow", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> changeInventoryRowAsync(WebServ1.InventoryFuncs.InventoryRow inventoryRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteInventoryRow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteInventoryRow(int id, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteInventoryRow", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteInventoryRowAsync(int id, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNewItemId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int getNewItemId(int UserId, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNewItemId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getNewItemIdAsync(int UserId, string email, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InventoryRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private float quantityField;
        
        private float neededQuantityField;
        
        private int ownerUserIdField;
        
        private float amountOutField;
        
        private string remarkesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float NeededQuantity {
            get {
                return this.neededQuantityField;
            }
            set {
                this.neededQuantityField = value;
                this.RaisePropertyChanged("NeededQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int OwnerUserId {
            get {
                return this.ownerUserIdField;
            }
            set {
                this.ownerUserIdField = value;
                this.RaisePropertyChanged("OwnerUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float AmountOut {
            get {
                return this.amountOutField;
            }
            set {
                this.amountOutField = value;
                this.RaisePropertyChanged("AmountOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Remarkes {
            get {
                return this.remarkesField;
            }
            set {
                this.remarkesField = value;
                this.RaisePropertyChanged("Remarkes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventoryFuncsSoapChannel : WebServ1.InventoryFuncs.InventoryFuncsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryFuncsSoapClient : System.ServiceModel.ClientBase<WebServ1.InventoryFuncs.InventoryFuncsSoap>, WebServ1.InventoryFuncs.InventoryFuncsSoap {
        
        public InventoryFuncsSoapClient() {
        }
        
        public InventoryFuncsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryFuncsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryFuncsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryFuncsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetInventoryUserDataTable(int userId, string email, string password) {
            return base.Channel.GetInventoryUserDataTable(userId, email, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetInventoryUserDataTableAsync(int userId, string email, string password) {
            return base.Channel.GetInventoryUserDataTableAsync(userId, email, password);
        }
        
        public bool changeInventoryRow(WebServ1.InventoryFuncs.InventoryRow inventoryRow) {
            return base.Channel.changeInventoryRow(inventoryRow);
        }
        
        public System.Threading.Tasks.Task<bool> changeInventoryRowAsync(WebServ1.InventoryFuncs.InventoryRow inventoryRow) {
            return base.Channel.changeInventoryRowAsync(inventoryRow);
        }
        
        public bool DeleteInventoryRow(int id, string email, string password) {
            return base.Channel.DeleteInventoryRow(id, email, password);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteInventoryRowAsync(int id, string email, string password) {
            return base.Channel.DeleteInventoryRowAsync(id, email, password);
        }
        
        public int getNewItemId(int UserId, string email, string password) {
            return base.Channel.getNewItemId(UserId, email, password);
        }
        
        public System.Threading.Tasks.Task<int> getNewItemIdAsync(int UserId, string email, string password) {
            return base.Channel.getNewItemIdAsync(UserId, email, password);
        }
    }
}
