//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.28307.1000
// 
namespace storageUniversal.BorowwDb {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Borrow", Namespace="http://tempuri.org/")]
    public partial class Borrow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ItemIdField;
        
        private string BorrowedByField;
        
        private System.DateTime WhenField;
        
        private float QuantityField;
        
        private float BorrowingIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BorrowedBy {
            get {
                return this.BorrowedByField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowedByField, value) != true)) {
                    this.BorrowedByField = value;
                    this.RaisePropertyChanged("BorrowedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime When {
            get {
                return this.WhenField;
            }
            set {
                if ((this.WhenField.Equals(value) != true)) {
                    this.WhenField = value;
                    this.RaisePropertyChanged("When");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float BorrowingId {
            get {
                return this.BorrowingIdField;
            }
            set {
                if ((this.BorrowingIdField.Equals(value) != true)) {
                    this.BorrowingIdField = value;
                    this.RaisePropertyChanged("BorrowingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BorowwDb.BorowwingsDBSoap")]
    public interface BorowwingsDBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<storageUniversal.BorowwDb.HelloWorldResponse> HelloWorldAsync(storageUniversal.BorowwDb.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLending", ReplyAction="*")]
        System.Threading.Tasks.Task<storageUniversal.BorowwDb.AddLendingResponse> AddLendingAsync(storageUniversal.BorowwDb.AddLendingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLandings", ReplyAction="*")]
        System.Threading.Tasks.Task<storageUniversal.BorowwDb.GetLandingsResponse> GetLandingsAsync(storageUniversal.BorowwDb.GetLandingsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public storageUniversal.BorowwDb.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(storageUniversal.BorowwDb.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public storageUniversal.BorowwDb.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(storageUniversal.BorowwDb.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLendingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLending", Namespace="http://tempuri.org/", Order=0)]
        public storageUniversal.BorowwDb.AddLendingRequestBody Body;
        
        public AddLendingRequest() {
        }
        
        public AddLendingRequest(storageUniversal.BorowwDb.AddLendingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLendingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lentForWho;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime whenBorowwed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float amountBorowwed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int userId;
        
        public AddLendingRequestBody() {
        }
        
        public AddLendingRequestBody(int itemId, string lentForWho, System.DateTime whenBorowwed, float amountBorowwed, int userId) {
            this.itemId = itemId;
            this.lentForWho = lentForWho;
            this.whenBorowwed = whenBorowwed;
            this.amountBorowwed = amountBorowwed;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddLendingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLendingResponse", Namespace="http://tempuri.org/", Order=0)]
        public storageUniversal.BorowwDb.AddLendingResponseBody Body;
        
        public AddLendingResponse() {
        }
        
        public AddLendingResponse(storageUniversal.BorowwDb.AddLendingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddLendingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddLendingResult;
        
        public AddLendingResponseBody() {
        }
        
        public AddLendingResponseBody(int AddLendingResult) {
            this.AddLendingResult = AddLendingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLandingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLandings", Namespace="http://tempuri.org/", Order=0)]
        public storageUniversal.BorowwDb.GetLandingsRequestBody Body;
        
        public GetLandingsRequest() {
        }
        
        public GetLandingsRequest(storageUniversal.BorowwDb.GetLandingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLandingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserId;
        
        public GetLandingsRequestBody() {
        }
        
        public GetLandingsRequestBody(int UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLandingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLandingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public storageUniversal.BorowwDb.GetLandingsResponseBody Body;
        
        public GetLandingsResponse() {
        }
        
        public GetLandingsResponse(storageUniversal.BorowwDb.GetLandingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLandingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<storageUniversal.BorowwDb.Borrow> GetLandingsResult;
        
        public GetLandingsResponseBody() {
        }
        
        public GetLandingsResponseBody(System.Collections.ObjectModel.ObservableCollection<storageUniversal.BorowwDb.Borrow> GetLandingsResult) {
            this.GetLandingsResult = GetLandingsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BorowwingsDBSoapChannel : storageUniversal.BorowwDb.BorowwingsDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BorowwingsDBSoapClient : System.ServiceModel.ClientBase<storageUniversal.BorowwDb.BorowwingsDBSoap>, storageUniversal.BorowwDb.BorowwingsDBSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BorowwingsDBSoapClient() : 
                base(BorowwingsDBSoapClient.GetDefaultBinding(), BorowwingsDBSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BorowwingsDBSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BorowwingsDBSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BorowwingsDBSoapClient.GetBindingForEndpoint(endpointConfiguration), BorowwingsDBSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BorowwingsDBSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BorowwingsDBSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BorowwingsDBSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BorowwingsDBSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BorowwingsDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<storageUniversal.BorowwDb.HelloWorldResponse> storageUniversal.BorowwDb.BorowwingsDBSoap.HelloWorldAsync(storageUniversal.BorowwDb.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<storageUniversal.BorowwDb.HelloWorldResponse> HelloWorldAsync() {
            storageUniversal.BorowwDb.HelloWorldRequest inValue = new storageUniversal.BorowwDb.HelloWorldRequest();
            inValue.Body = new storageUniversal.BorowwDb.HelloWorldRequestBody();
            return ((storageUniversal.BorowwDb.BorowwingsDBSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<storageUniversal.BorowwDb.AddLendingResponse> storageUniversal.BorowwDb.BorowwingsDBSoap.AddLendingAsync(storageUniversal.BorowwDb.AddLendingRequest request) {
            return base.Channel.AddLendingAsync(request);
        }
        
        public System.Threading.Tasks.Task<storageUniversal.BorowwDb.AddLendingResponse> AddLendingAsync(int itemId, string lentForWho, System.DateTime whenBorowwed, float amountBorowwed, int userId) {
            storageUniversal.BorowwDb.AddLendingRequest inValue = new storageUniversal.BorowwDb.AddLendingRequest();
            inValue.Body = new storageUniversal.BorowwDb.AddLendingRequestBody();
            inValue.Body.itemId = itemId;
            inValue.Body.lentForWho = lentForWho;
            inValue.Body.whenBorowwed = whenBorowwed;
            inValue.Body.amountBorowwed = amountBorowwed;
            inValue.Body.userId = userId;
            return ((storageUniversal.BorowwDb.BorowwingsDBSoap)(this)).AddLendingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<storageUniversal.BorowwDb.GetLandingsResponse> storageUniversal.BorowwDb.BorowwingsDBSoap.GetLandingsAsync(storageUniversal.BorowwDb.GetLandingsRequest request) {
            return base.Channel.GetLandingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<storageUniversal.BorowwDb.GetLandingsResponse> GetLandingsAsync(int UserId) {
            storageUniversal.BorowwDb.GetLandingsRequest inValue = new storageUniversal.BorowwDb.GetLandingsRequest();
            inValue.Body = new storageUniversal.BorowwDb.GetLandingsRequestBody();
            inValue.Body.UserId = UserId;
            return ((storageUniversal.BorowwDb.BorowwingsDBSoap)(this)).GetLandingsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BorowwingsDBSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BorowwingsDBSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:50581/BorowwingsDB.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return BorowwingsDBSoapClient.GetBindingForEndpoint(EndpointConfiguration.BorowwingsDBSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return BorowwingsDBSoapClient.GetEndpointAddress(EndpointConfiguration.BorowwingsDBSoap);
        }
        
        public enum EndpointConfiguration {
            
            BorowwingsDBSoap,
        }
    }
}
